version: '3'
services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
    command: npm start
    env_file:
      - .env
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx/ssl:/etc/nginx/ssl'
    depends_on:
      - frontend
